DROP TABLE CONTACT_TBL;
CREATE TABLE CONTACT_TBL (
    CONTACT_NO  NUMBER              NOT NULL,
    NAME        VARCHAR2(20 BYTE)   NOT NULL,
    TEL         VARCHAR2(20 BYTE)   NULL,
    EMAIL       VARCHAR2(99 BYTE)   NULL,
    ADDRESS     VARCHAR2(99 BYTE)   NULL
);

ALTER TABLE CONTACT_TBL
    ADD CONSTRAINT PK_CONTACT PRIMARY KEY(CONTACT_NO);
    
DROP SEQUENCE CONTACT_SEQ;
CREATE SEQUENCE CONTACT_SEQ NOCACHE;

SELECT CONTACT_NO, NAME, TEL, EMAIL, ADDRESS
  FROM CONTACT_TBL;


INSERT INTO CONTACT_TBL VALUES (CONTACT_SEQ.NEXTVAL, '상철', '010-1111-1111', 'sangcheol@naver.com', '제주');
INSERT INTO CONTACT_TBL VALUES (CONTACT_SEQ.NEXTVAL, '관리실', '02-1111-1111', 'admin@naver.com', '서울');
INSERT INTO CONTACT_TBL VALUES (CONTACT_SEQ.NEXTVAL, '미자', '010-3213-6594', 'miza@naver.com', '안양');
INSERT INTO CONTACT_TBL VALUES (CONTACT_SEQ.NEXTVAL, '철수', '010-9405-0684', 'cheolsoo@naver.com', '인천');
INSERT INTO CONTACT_TBL VALUES (CONTACT_SEQ.NEXTVAL, '상철', '010-9852-2334', 'ceoldsa@naver.com', '인천');



 